/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceProjectIdRouteImport } from './routes/workspace.$projectId'
import { Route as WorkspaceProjectIdIndexRouteImport } from './routes/workspace.$projectId.index'
import { Route as WorkspaceProjectIdReviewerRouteImport } from './routes/workspace.$projectId.reviewer'
import { Route as WorkspaceProjectIdResearchRouteImport } from './routes/workspace.$projectId.research'
import { Route as WorkspaceProjectIdPapersRouteImport } from './routes/workspace.$projectId.papers'
import { Route as WorkspaceProjectIdKnowledgeRouteImport } from './routes/workspace.$projectId.knowledge'
import { Route as WorkspaceProjectIdExportRouteImport } from './routes/workspace.$projectId.export'
import { Route as WorkspaceProjectIdEditorRouteImport } from './routes/workspace.$projectId.editor'
import { Route as WorkspaceProjectIdDraftsRouteImport } from './routes/workspace.$projectId.drafts'
import { Route as WorkspaceProjectIdAiStudioRouteImport } from './routes/workspace.$projectId.ai-studio'
import { Route as WorkspaceProjectIdDraftsIndexRouteImport } from './routes/workspace.$projectId.drafts.index'
import { Route as WorkspaceProjectIdDraftsDraftIdRouteImport } from './routes/workspace.$projectId.drafts.$draftId'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceProjectIdRoute = WorkspaceProjectIdRouteImport.update({
  id: '/workspace/$projectId',
  path: '/workspace/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceProjectIdIndexRoute = WorkspaceProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceProjectIdRoute,
} as any)
const WorkspaceProjectIdReviewerRoute =
  WorkspaceProjectIdReviewerRouteImport.update({
    id: '/reviewer',
    path: '/reviewer',
    getParentRoute: () => WorkspaceProjectIdRoute,
  } as any)
const WorkspaceProjectIdResearchRoute =
  WorkspaceProjectIdResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => WorkspaceProjectIdRoute,
  } as any)
const WorkspaceProjectIdPapersRoute =
  WorkspaceProjectIdPapersRouteImport.update({
    id: '/papers',
    path: '/papers',
    getParentRoute: () => WorkspaceProjectIdRoute,
  } as any)
const WorkspaceProjectIdKnowledgeRoute =
  WorkspaceProjectIdKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => WorkspaceProjectIdRoute,
  } as any)
const WorkspaceProjectIdExportRoute =
  WorkspaceProjectIdExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => WorkspaceProjectIdRoute,
  } as any)
const WorkspaceProjectIdEditorRoute =
  WorkspaceProjectIdEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => WorkspaceProjectIdRoute,
  } as any)
const WorkspaceProjectIdDraftsRoute =
  WorkspaceProjectIdDraftsRouteImport.update({
    id: '/drafts',
    path: '/drafts',
    getParentRoute: () => WorkspaceProjectIdRoute,
  } as any)
const WorkspaceProjectIdAiStudioRoute =
  WorkspaceProjectIdAiStudioRouteImport.update({
    id: '/ai-studio',
    path: '/ai-studio',
    getParentRoute: () => WorkspaceProjectIdRoute,
  } as any)
const WorkspaceProjectIdDraftsIndexRoute =
  WorkspaceProjectIdDraftsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceProjectIdDraftsRoute,
  } as any)
const WorkspaceProjectIdDraftsDraftIdRoute =
  WorkspaceProjectIdDraftsDraftIdRouteImport.update({
    id: '/$draftId',
    path: '/$draftId',
    getParentRoute: () => WorkspaceProjectIdDraftsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdRouteWithChildren
  '/workspace/$projectId/ai-studio': typeof WorkspaceProjectIdAiStudioRoute
  '/workspace/$projectId/drafts': typeof WorkspaceProjectIdDraftsRouteWithChildren
  '/workspace/$projectId/editor': typeof WorkspaceProjectIdEditorRoute
  '/workspace/$projectId/export': typeof WorkspaceProjectIdExportRoute
  '/workspace/$projectId/knowledge': typeof WorkspaceProjectIdKnowledgeRoute
  '/workspace/$projectId/papers': typeof WorkspaceProjectIdPapersRoute
  '/workspace/$projectId/research': typeof WorkspaceProjectIdResearchRoute
  '/workspace/$projectId/reviewer': typeof WorkspaceProjectIdReviewerRoute
  '/workspace/$projectId/': typeof WorkspaceProjectIdIndexRoute
  '/workspace/$projectId/drafts/$draftId': typeof WorkspaceProjectIdDraftsDraftIdRoute
  '/workspace/$projectId/drafts/': typeof WorkspaceProjectIdDraftsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/workspace/$projectId/ai-studio': typeof WorkspaceProjectIdAiStudioRoute
  '/workspace/$projectId/editor': typeof WorkspaceProjectIdEditorRoute
  '/workspace/$projectId/export': typeof WorkspaceProjectIdExportRoute
  '/workspace/$projectId/knowledge': typeof WorkspaceProjectIdKnowledgeRoute
  '/workspace/$projectId/papers': typeof WorkspaceProjectIdPapersRoute
  '/workspace/$projectId/research': typeof WorkspaceProjectIdResearchRoute
  '/workspace/$projectId/reviewer': typeof WorkspaceProjectIdReviewerRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdIndexRoute
  '/workspace/$projectId/drafts/$draftId': typeof WorkspaceProjectIdDraftsDraftIdRoute
  '/workspace/$projectId/drafts': typeof WorkspaceProjectIdDraftsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdRouteWithChildren
  '/workspace/$projectId/ai-studio': typeof WorkspaceProjectIdAiStudioRoute
  '/workspace/$projectId/drafts': typeof WorkspaceProjectIdDraftsRouteWithChildren
  '/workspace/$projectId/editor': typeof WorkspaceProjectIdEditorRoute
  '/workspace/$projectId/export': typeof WorkspaceProjectIdExportRoute
  '/workspace/$projectId/knowledge': typeof WorkspaceProjectIdKnowledgeRoute
  '/workspace/$projectId/papers': typeof WorkspaceProjectIdPapersRoute
  '/workspace/$projectId/research': typeof WorkspaceProjectIdResearchRoute
  '/workspace/$projectId/reviewer': typeof WorkspaceProjectIdReviewerRoute
  '/workspace/$projectId/': typeof WorkspaceProjectIdIndexRoute
  '/workspace/$projectId/drafts/$draftId': typeof WorkspaceProjectIdDraftsDraftIdRoute
  '/workspace/$projectId/drafts/': typeof WorkspaceProjectIdDraftsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/workspace/$projectId'
    | '/workspace/$projectId/ai-studio'
    | '/workspace/$projectId/drafts'
    | '/workspace/$projectId/editor'
    | '/workspace/$projectId/export'
    | '/workspace/$projectId/knowledge'
    | '/workspace/$projectId/papers'
    | '/workspace/$projectId/research'
    | '/workspace/$projectId/reviewer'
    | '/workspace/$projectId/'
    | '/workspace/$projectId/drafts/$draftId'
    | '/workspace/$projectId/drafts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/workspace/$projectId/ai-studio'
    | '/workspace/$projectId/editor'
    | '/workspace/$projectId/export'
    | '/workspace/$projectId/knowledge'
    | '/workspace/$projectId/papers'
    | '/workspace/$projectId/research'
    | '/workspace/$projectId/reviewer'
    | '/workspace/$projectId'
    | '/workspace/$projectId/drafts/$draftId'
    | '/workspace/$projectId/drafts'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/workspace/$projectId'
    | '/workspace/$projectId/ai-studio'
    | '/workspace/$projectId/drafts'
    | '/workspace/$projectId/editor'
    | '/workspace/$projectId/export'
    | '/workspace/$projectId/knowledge'
    | '/workspace/$projectId/papers'
    | '/workspace/$projectId/research'
    | '/workspace/$projectId/reviewer'
    | '/workspace/$projectId/'
    | '/workspace/$projectId/drafts/$draftId'
    | '/workspace/$projectId/drafts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  WorkspaceProjectIdRoute: typeof WorkspaceProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$projectId': {
      id: '/workspace/$projectId'
      path: '/workspace/$projectId'
      fullPath: '/workspace/$projectId'
      preLoaderRoute: typeof WorkspaceProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$projectId/': {
      id: '/workspace/$projectId/'
      path: '/'
      fullPath: '/workspace/$projectId/'
      preLoaderRoute: typeof WorkspaceProjectIdIndexRouteImport
      parentRoute: typeof WorkspaceProjectIdRoute
    }
    '/workspace/$projectId/reviewer': {
      id: '/workspace/$projectId/reviewer'
      path: '/reviewer'
      fullPath: '/workspace/$projectId/reviewer'
      preLoaderRoute: typeof WorkspaceProjectIdReviewerRouteImport
      parentRoute: typeof WorkspaceProjectIdRoute
    }
    '/workspace/$projectId/research': {
      id: '/workspace/$projectId/research'
      path: '/research'
      fullPath: '/workspace/$projectId/research'
      preLoaderRoute: typeof WorkspaceProjectIdResearchRouteImport
      parentRoute: typeof WorkspaceProjectIdRoute
    }
    '/workspace/$projectId/papers': {
      id: '/workspace/$projectId/papers'
      path: '/papers'
      fullPath: '/workspace/$projectId/papers'
      preLoaderRoute: typeof WorkspaceProjectIdPapersRouteImport
      parentRoute: typeof WorkspaceProjectIdRoute
    }
    '/workspace/$projectId/knowledge': {
      id: '/workspace/$projectId/knowledge'
      path: '/knowledge'
      fullPath: '/workspace/$projectId/knowledge'
      preLoaderRoute: typeof WorkspaceProjectIdKnowledgeRouteImport
      parentRoute: typeof WorkspaceProjectIdRoute
    }
    '/workspace/$projectId/export': {
      id: '/workspace/$projectId/export'
      path: '/export'
      fullPath: '/workspace/$projectId/export'
      preLoaderRoute: typeof WorkspaceProjectIdExportRouteImport
      parentRoute: typeof WorkspaceProjectIdRoute
    }
    '/workspace/$projectId/editor': {
      id: '/workspace/$projectId/editor'
      path: '/editor'
      fullPath: '/workspace/$projectId/editor'
      preLoaderRoute: typeof WorkspaceProjectIdEditorRouteImport
      parentRoute: typeof WorkspaceProjectIdRoute
    }
    '/workspace/$projectId/drafts': {
      id: '/workspace/$projectId/drafts'
      path: '/drafts'
      fullPath: '/workspace/$projectId/drafts'
      preLoaderRoute: typeof WorkspaceProjectIdDraftsRouteImport
      parentRoute: typeof WorkspaceProjectIdRoute
    }
    '/workspace/$projectId/ai-studio': {
      id: '/workspace/$projectId/ai-studio'
      path: '/ai-studio'
      fullPath: '/workspace/$projectId/ai-studio'
      preLoaderRoute: typeof WorkspaceProjectIdAiStudioRouteImport
      parentRoute: typeof WorkspaceProjectIdRoute
    }
    '/workspace/$projectId/drafts/': {
      id: '/workspace/$projectId/drafts/'
      path: '/'
      fullPath: '/workspace/$projectId/drafts/'
      preLoaderRoute: typeof WorkspaceProjectIdDraftsIndexRouteImport
      parentRoute: typeof WorkspaceProjectIdDraftsRoute
    }
    '/workspace/$projectId/drafts/$draftId': {
      id: '/workspace/$projectId/drafts/$draftId'
      path: '/$draftId'
      fullPath: '/workspace/$projectId/drafts/$draftId'
      preLoaderRoute: typeof WorkspaceProjectIdDraftsDraftIdRouteImport
      parentRoute: typeof WorkspaceProjectIdDraftsRoute
    }
  }
}

interface WorkspaceProjectIdDraftsRouteChildren {
  WorkspaceProjectIdDraftsDraftIdRoute: typeof WorkspaceProjectIdDraftsDraftIdRoute
  WorkspaceProjectIdDraftsIndexRoute: typeof WorkspaceProjectIdDraftsIndexRoute
}

const WorkspaceProjectIdDraftsRouteChildren: WorkspaceProjectIdDraftsRouteChildren =
  {
    WorkspaceProjectIdDraftsDraftIdRoute: WorkspaceProjectIdDraftsDraftIdRoute,
    WorkspaceProjectIdDraftsIndexRoute: WorkspaceProjectIdDraftsIndexRoute,
  }

const WorkspaceProjectIdDraftsRouteWithChildren =
  WorkspaceProjectIdDraftsRoute._addFileChildren(
    WorkspaceProjectIdDraftsRouteChildren,
  )

interface WorkspaceProjectIdRouteChildren {
  WorkspaceProjectIdAiStudioRoute: typeof WorkspaceProjectIdAiStudioRoute
  WorkspaceProjectIdDraftsRoute: typeof WorkspaceProjectIdDraftsRouteWithChildren
  WorkspaceProjectIdEditorRoute: typeof WorkspaceProjectIdEditorRoute
  WorkspaceProjectIdExportRoute: typeof WorkspaceProjectIdExportRoute
  WorkspaceProjectIdKnowledgeRoute: typeof WorkspaceProjectIdKnowledgeRoute
  WorkspaceProjectIdPapersRoute: typeof WorkspaceProjectIdPapersRoute
  WorkspaceProjectIdResearchRoute: typeof WorkspaceProjectIdResearchRoute
  WorkspaceProjectIdReviewerRoute: typeof WorkspaceProjectIdReviewerRoute
  WorkspaceProjectIdIndexRoute: typeof WorkspaceProjectIdIndexRoute
}

const WorkspaceProjectIdRouteChildren: WorkspaceProjectIdRouteChildren = {
  WorkspaceProjectIdAiStudioRoute: WorkspaceProjectIdAiStudioRoute,
  WorkspaceProjectIdDraftsRoute: WorkspaceProjectIdDraftsRouteWithChildren,
  WorkspaceProjectIdEditorRoute: WorkspaceProjectIdEditorRoute,
  WorkspaceProjectIdExportRoute: WorkspaceProjectIdExportRoute,
  WorkspaceProjectIdKnowledgeRoute: WorkspaceProjectIdKnowledgeRoute,
  WorkspaceProjectIdPapersRoute: WorkspaceProjectIdPapersRoute,
  WorkspaceProjectIdResearchRoute: WorkspaceProjectIdResearchRoute,
  WorkspaceProjectIdReviewerRoute: WorkspaceProjectIdReviewerRoute,
  WorkspaceProjectIdIndexRoute: WorkspaceProjectIdIndexRoute,
}

const WorkspaceProjectIdRouteWithChildren =
  WorkspaceProjectIdRoute._addFileChildren(WorkspaceProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  WorkspaceProjectIdRoute: WorkspaceProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
