from app.models.draft_section import DraftSectionType

def normalize_heading(heading: str) -> str:
    return " ".join(heading.strip().lower().split())

SECTION_MAP = {
    "abstract": DraftSectionType.ABSTRACT,
    "introduction": DraftSectionType.INTRODUCTION,
    "related work": DraftSectionType.RELATED_WORK,
    "methodology": DraftSectionType.METHODOLOGY,
    "experiments": DraftSectionType.EXPERIMENTS,
    "results": DraftSectionType.RESULTS,
    "discussion": DraftSectionType.DISCUSSION,
    "conclusion": DraftSectionType.CONCLUSION,
}




def parse_paper(markdown: str):
    """
    Parses markdown generated by build_full_paper().
    Returns:
    {
        DraftSectionType: content
    }
    """

    sections = {}

    current = None
    buffer = []

    for line in markdown.splitlines():

        if line.startswith("## "):

            if current:
                sections[current] = "\n".join(buffer).strip()

            title = normalize_heading(line.removeprefix("## "))
            current = SECTION_MAP.get(title)

            buffer = []

            continue

        if current:
            buffer.append(line)

    if current:
        sections[current] = "\n".join(buffer).strip()

    return sections